-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Network.PB.ActivityType')


local __PBTABLE__ = {}

__PBTABLE__.ACTIVITYTYPE = protobuf.EnumDescriptor();
_M.ACTIVITYTYPE = __PBTABLE__.ACTIVITYTYPE

__PBTABLE__.ACTIVITYTYPE_SALE_ENUM = protobuf.EnumValueDescriptor();

__PBTABLE__.ACTIVITYTYPE_SALE_ENUM.name = "Sale"
__PBTABLE__.ACTIVITYTYPE_SALE_ENUM.index = 0
__PBTABLE__.ACTIVITYTYPE_SALE_ENUM.number = 100
__PBTABLE__.ACTIVITYTYPE.name = "ActivityType"
__PBTABLE__.ACTIVITYTYPE.full_name = ".PB.ActivityType"
__PBTABLE__.ACTIVITYTYPE.values = {__PBTABLE__.ACTIVITYTYPE_SALE_ENUM}

Sale = 100

