-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local ProtocolId = require("Network.PB.ProtocolId")
local HeadMessage = require("Network.PB.HeadMessage")
module('Network.PB.C2SBuyRequest')


local __PBTABLE__ = {}

local BUYREQUEST = protobuf.Descriptor();
_M.BUYREQUEST = BUYREQUEST

__PBTABLE__.BUYREQUEST_ID_FIELD = protobuf.FieldDescriptor();
__PBTABLE__.BUYREQUEST_HEAD_FIELD = protobuf.FieldDescriptor();

__PBTABLE__.BUYREQUEST_ID_FIELD.name = "id"
__PBTABLE__.BUYREQUEST_ID_FIELD.full_name = ".PB.BuyRequest.id"
__PBTABLE__.BUYREQUEST_ID_FIELD.number = 1
__PBTABLE__.BUYREQUEST_ID_FIELD.index = 0
__PBTABLE__.BUYREQUEST_ID_FIELD.label = 1
__PBTABLE__.BUYREQUEST_ID_FIELD.has_default_value = true
__PBTABLE__.BUYREQUEST_ID_FIELD.default_value = "ACT_TOWER_SHOP_BUY_REQUEST_MESSAGE"
__PBTABLE__.BUYREQUEST_ID_FIELD.enum_type = PROTOCOLID or ProtocolId.PROTOCOLID
__PBTABLE__.BUYREQUEST_ID_FIELD.type = 14
__PBTABLE__.BUYREQUEST_ID_FIELD.cpp_type = 8

__PBTABLE__.BUYREQUEST_HEAD_FIELD.name = "head"
__PBTABLE__.BUYREQUEST_HEAD_FIELD.full_name = ".PB.BuyRequest.head"
__PBTABLE__.BUYREQUEST_HEAD_FIELD.number = 2
__PBTABLE__.BUYREQUEST_HEAD_FIELD.index = 1
__PBTABLE__.BUYREQUEST_HEAD_FIELD.label = 1
__PBTABLE__.BUYREQUEST_HEAD_FIELD.has_default_value = false
__PBTABLE__.BUYREQUEST_HEAD_FIELD.default_value = nil
__PBTABLE__.BUYREQUEST_HEAD_FIELD.message_type = HEADMESSAGE or HeadMessage.HEADMESSAGE
__PBTABLE__.BUYREQUEST_HEAD_FIELD.type = 11
__PBTABLE__.BUYREQUEST_HEAD_FIELD.cpp_type = 10

BUYREQUEST.name = "BuyRequest"
BUYREQUEST.full_name = ".PB.BuyRequest"
BUYREQUEST.nested_types = {}
BUYREQUEST.enum_types = {}
BUYREQUEST.fields = {__PBTABLE__.BUYREQUEST_ID_FIELD, __PBTABLE__.BUYREQUEST_HEAD_FIELD}
BUYREQUEST.is_extendable = false
BUYREQUEST.extensions = {}

BuyRequest = protobuf.Message(BUYREQUEST)

