-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local ProtocolId = require("Network.PB.ProtocolId")
local HeadMessage = require("Network.PB.HeadMessage")
module('Network.PB.C2SMailRequest')


local __PBTABLE__ = {}

local MAILREQUEST = protobuf.Descriptor();
_M.MAILREQUEST = MAILREQUEST

__PBTABLE__.MAILREQUEST_ID_FIELD = protobuf.FieldDescriptor();
__PBTABLE__.MAILREQUEST_HEAD_FIELD = protobuf.FieldDescriptor();

__PBTABLE__.MAILREQUEST_ID_FIELD.name = "id"
__PBTABLE__.MAILREQUEST_ID_FIELD.full_name = ".PB.MailRequest.id"
__PBTABLE__.MAILREQUEST_ID_FIELD.number = 1
__PBTABLE__.MAILREQUEST_ID_FIELD.index = 0
__PBTABLE__.MAILREQUEST_ID_FIELD.label = 1
__PBTABLE__.MAILREQUEST_ID_FIELD.has_default_value = true
__PBTABLE__.MAILREQUEST_ID_FIELD.default_value = "ACT_MAIL_MAIL_REQUEST_MESSAGE"
__PBTABLE__.MAILREQUEST_ID_FIELD.enum_type = PROTOCOLID or ProtocolId.PROTOCOLID
__PBTABLE__.MAILREQUEST_ID_FIELD.type = 14
__PBTABLE__.MAILREQUEST_ID_FIELD.cpp_type = 8

__PBTABLE__.MAILREQUEST_HEAD_FIELD.name = "head"
__PBTABLE__.MAILREQUEST_HEAD_FIELD.full_name = ".PB.MailRequest.head"
__PBTABLE__.MAILREQUEST_HEAD_FIELD.number = 2
__PBTABLE__.MAILREQUEST_HEAD_FIELD.index = 1
__PBTABLE__.MAILREQUEST_HEAD_FIELD.label = 1
__PBTABLE__.MAILREQUEST_HEAD_FIELD.has_default_value = false
__PBTABLE__.MAILREQUEST_HEAD_FIELD.default_value = nil
__PBTABLE__.MAILREQUEST_HEAD_FIELD.message_type = HEADMESSAGE or HeadMessage.HEADMESSAGE
__PBTABLE__.MAILREQUEST_HEAD_FIELD.type = 11
__PBTABLE__.MAILREQUEST_HEAD_FIELD.cpp_type = 10

MAILREQUEST.name = "MailRequest"
MAILREQUEST.full_name = ".PB.MailRequest"
MAILREQUEST.nested_types = {}
MAILREQUEST.enum_types = {}
MAILREQUEST.fields = {__PBTABLE__.MAILREQUEST_ID_FIELD, __PBTABLE__.MAILREQUEST_HEAD_FIELD}
MAILREQUEST.is_extendable = false
MAILREQUEST.extensions = {}

MailRequest = protobuf.Message(MAILREQUEST)

