-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local ProtocolId = require("Network.PB.ProtocolId")
local HeadMessage = require("Network.PB.HeadMessage")
module('Network.PB.C2SPing')


local __PBTABLE__ = {}

local PINGMESSAGE = protobuf.Descriptor();
_M.PINGMESSAGE = PINGMESSAGE

__PBTABLE__.PINGMESSAGE_ID_FIELD = protobuf.FieldDescriptor();
__PBTABLE__.PINGMESSAGE_HEAD_FIELD = protobuf.FieldDescriptor();
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD = protobuf.FieldDescriptor();

__PBTABLE__.PINGMESSAGE_ID_FIELD.name = "id"
__PBTABLE__.PINGMESSAGE_ID_FIELD.full_name = ".PB.PingMessage.id"
__PBTABLE__.PINGMESSAGE_ID_FIELD.number = 1
__PBTABLE__.PINGMESSAGE_ID_FIELD.index = 0
__PBTABLE__.PINGMESSAGE_ID_FIELD.label = 1
__PBTABLE__.PINGMESSAGE_ID_FIELD.has_default_value = true
__PBTABLE__.PINGMESSAGE_ID_FIELD.default_value = "ACT_ACCOUNT_PING_MESSAGE"
__PBTABLE__.PINGMESSAGE_ID_FIELD.enum_type = PROTOCOLID or ProtocolId.PROTOCOLID
__PBTABLE__.PINGMESSAGE_ID_FIELD.type = 14
__PBTABLE__.PINGMESSAGE_ID_FIELD.cpp_type = 8

__PBTABLE__.PINGMESSAGE_HEAD_FIELD.name = "head"
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.full_name = ".PB.PingMessage.head"
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.number = 2
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.index = 1
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.label = 1
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.has_default_value = false
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.default_value = nil
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.message_type = HEADMESSAGE or HeadMessage.HEADMESSAGE
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.type = 11
__PBTABLE__.PINGMESSAGE_HEAD_FIELD.cpp_type = 10

__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.name = "pingValue"
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.full_name = ".PB.PingMessage.pingValue"
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.number = 3
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.index = 2
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.label = 1
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.has_default_value = false
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.default_value = 0
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.type = 5
__PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD.cpp_type = 1

PINGMESSAGE.name = "PingMessage"
PINGMESSAGE.full_name = ".PB.PingMessage"
PINGMESSAGE.nested_types = {}
PINGMESSAGE.enum_types = {}
PINGMESSAGE.fields = {__PBTABLE__.PINGMESSAGE_ID_FIELD, __PBTABLE__.PINGMESSAGE_HEAD_FIELD, __PBTABLE__.PINGMESSAGE_PINGVALUE_FIELD}
PINGMESSAGE.is_extendable = false
PINGMESSAGE.extensions = {}

PingMessage = protobuf.Message(PINGMESSAGE)

