-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local ProtocolId = require("Network.PB.ProtocolId")
local HeadMessage = require("Network.PB.HeadMessage")
module('Network.PB.C2SVipChargeQuery')


local __PBTABLE__ = {}

local VIPCHARGEQUERY = protobuf.Descriptor();
_M.VIPCHARGEQUERY = VIPCHARGEQUERY

__PBTABLE__.VIPCHARGEQUERY_ID_FIELD = protobuf.FieldDescriptor();
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD = protobuf.FieldDescriptor();

__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.name = "id"
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.full_name = ".PB.VipChargeQuery.id"
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.number = 1
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.index = 0
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.label = 1
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.has_default_value = true
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.default_value = "ACT_VIP_VIP_CHARGE_QUERY_REQUEST"
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.enum_type = PROTOCOLID or ProtocolId.PROTOCOLID
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.type = 14
__PBTABLE__.VIPCHARGEQUERY_ID_FIELD.cpp_type = 8

__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.name = "head"
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.full_name = ".PB.VipChargeQuery.head"
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.number = 2
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.index = 1
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.label = 1
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.has_default_value = false
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.default_value = nil
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.message_type = HEADMESSAGE or HeadMessage.HEADMESSAGE
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.type = 11
__PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD.cpp_type = 10

VIPCHARGEQUERY.name = "VipChargeQuery"
VIPCHARGEQUERY.full_name = ".PB.VipChargeQuery"
VIPCHARGEQUERY.nested_types = {}
VIPCHARGEQUERY.enum_types = {}
VIPCHARGEQUERY.fields = {__PBTABLE__.VIPCHARGEQUERY_ID_FIELD, __PBTABLE__.VIPCHARGEQUERY_HEAD_FIELD}
VIPCHARGEQUERY.is_extendable = false
VIPCHARGEQUERY.extensions = {}

VipChargeQuery = protobuf.Message(VIPCHARGEQUERY)

