-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
local ProtocolId = require("Network.PB.ProtocolId")
local HeadMessage = require("Network.PB.HeadMessage")
module('Network.PB.S2CQuitGameResult')


local __PBTABLE__ = {}

local QUITGAMERESULT = protobuf.Descriptor();
_M.QUITGAMERESULT = QUITGAMERESULT

__PBTABLE__.QUITGAMERESULT_ID_FIELD = protobuf.FieldDescriptor();
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD = protobuf.FieldDescriptor();

__PBTABLE__.QUITGAMERESULT_ID_FIELD.name = "id"
__PBTABLE__.QUITGAMERESULT_ID_FIELD.full_name = ".PB.QuitGameResult.id"
__PBTABLE__.QUITGAMERESULT_ID_FIELD.number = 1
__PBTABLE__.QUITGAMERESULT_ID_FIELD.index = 0
__PBTABLE__.QUITGAMERESULT_ID_FIELD.label = 1
__PBTABLE__.QUITGAMERESULT_ID_FIELD.has_default_value = true
__PBTABLE__.QUITGAMERESULT_ID_FIELD.default_value = "SND_ACCOUNT_CREATE_PLAYER_RESULT_MESSAGE"
__PBTABLE__.QUITGAMERESULT_ID_FIELD.enum_type = PROTOCOLID or ProtocolId.PROTOCOLID
__PBTABLE__.QUITGAMERESULT_ID_FIELD.type = 14
__PBTABLE__.QUITGAMERESULT_ID_FIELD.cpp_type = 8

__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.name = "head"
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.full_name = ".PB.QuitGameResult.head"
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.number = 2
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.index = 1
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.label = 1
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.has_default_value = false
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.default_value = nil
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.message_type = HEADMESSAGE or HeadMessage.HEADMESSAGE
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.type = 11
__PBTABLE__.QUITGAMERESULT_HEAD_FIELD.cpp_type = 10

QUITGAMERESULT.name = "QuitGameResult"
QUITGAMERESULT.full_name = ".PB.QuitGameResult"
QUITGAMERESULT.nested_types = {}
QUITGAMERESULT.enum_types = {}
QUITGAMERESULT.fields = {__PBTABLE__.QUITGAMERESULT_ID_FIELD, __PBTABLE__.QUITGAMERESULT_HEAD_FIELD}
QUITGAMERESULT.is_extendable = false
QUITGAMERESULT.extensions = {}

QuitGameResult = protobuf.Message(QUITGAMERESULT)

