-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf.protobuf"
module('Network.PB.TarotState')


local __PBTABLE__ = {}

local TAROTSTATE = protobuf.Descriptor();
_M.TAROTSTATE = TAROTSTATE

__PBTABLE__.TAROTSTATE_ID_FIELD = protobuf.FieldDescriptor();
__PBTABLE__.TAROTSTATE_FLAGS_FIELD = protobuf.FieldDescriptor();

__PBTABLE__.TAROTSTATE_ID_FIELD.name = "id"
__PBTABLE__.TAROTSTATE_ID_FIELD.full_name = ".PB.TarotState.id"
__PBTABLE__.TAROTSTATE_ID_FIELD.number = 1
__PBTABLE__.TAROTSTATE_ID_FIELD.index = 0
__PBTABLE__.TAROTSTATE_ID_FIELD.label = 2
__PBTABLE__.TAROTSTATE_ID_FIELD.has_default_value = false
__PBTABLE__.TAROTSTATE_ID_FIELD.default_value = 0
__PBTABLE__.TAROTSTATE_ID_FIELD.type = 5
__PBTABLE__.TAROTSTATE_ID_FIELD.cpp_type = 1

__PBTABLE__.TAROTSTATE_FLAGS_FIELD.name = "flags"
__PBTABLE__.TAROTSTATE_FLAGS_FIELD.full_name = ".PB.TarotState.flags"
__PBTABLE__.TAROTSTATE_FLAGS_FIELD.number = 2
__PBTABLE__.TAROTSTATE_FLAGS_FIELD.index = 1
__PBTABLE__.TAROTSTATE_FLAGS_FIELD.label = 2
__PBTABLE__.TAROTSTATE_FLAGS_FIELD.has_default_value = false
__PBTABLE__.TAROTSTATE_FLAGS_FIELD.default_value = 0
__PBTABLE__.TAROTSTATE_FLAGS_FIELD.type = 5
__PBTABLE__.TAROTSTATE_FLAGS_FIELD.cpp_type = 1

TAROTSTATE.name = "TarotState"
TAROTSTATE.full_name = ".PB.TarotState"
TAROTSTATE.nested_types = {}
TAROTSTATE.enum_types = {}
TAROTSTATE.fields = {__PBTABLE__.TAROTSTATE_ID_FIELD, __PBTABLE__.TAROTSTATE_FLAGS_FIELD}
TAROTSTATE.is_extendable = false
TAROTSTATE.extensions = {}

TarotState = protobuf.Message(TAROTSTATE)

